"use client";
import Image from "next/image";
import "./globals.css";
import { useEffect, useState, useContext } from "react";
import { GlobalContext } from "./context/context";
import { useRouter } from "next/navigation";
import Head from "next/head";
import { Spinner } from "@chakra-ui/react";
export default function Home() {
  const { authenticated } = useContext(GlobalContext);
  const router = useRouter();
  useEffect(() => {
    if (!authenticated) {
      router.push("/login");
    }
  }, []);

  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <Head>
        <title>ByteBreach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {authenticated ? "Welcome to ByteBreach..." : <Spinner />}
    </main>
  );
}
